bookmark/urls.py
from django.urls import path
from .views import list, new, edit, delete

app_name = 'bookmark'

urlpatterns = [
    path('', list, name='list'),
    path('new/', new, name='new'),
    path('edit/<int:pk>', edit, name='edit'),
    path('delete/<int:pk>', delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookmark.urls')),
]

bookmark/models.py
from django.db import models

class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    url = models.CharField(max_length=1000)

bookmark/forms.py
from django import forms
from .models import Bookmark

class BookmarkForm(forms.ModelForm):
    site_name = forms.CharField(label='사이트명')
    url = forms.CharField(label='주소')

    class Meta:
        model = Bookmark
        fields = '__all__'

bookmark/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Bookmark
from .forms import BookmarkForm


def list(request):
    list = Bookmark.objects.all()

    return render(request, 'bookmark/list.html', {
        'list': list,
    })

def new(request):
    if request.method == 'POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = Bookmark()
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.url = form.cleaned_data['url']
            bookmark.save()
            return redirect('bookmark:list')
    else:
        form = BookmarkForm()
    return render(request, 'bookmark/new.html', {
        'form': form,
    })

def edit(request, pk):
    bookmark = get_object_or_404(Bookmark, pk=pk)

    if request.method =='POST':
        form = BookmarkForm(request.POST, instance=bookmark)
        if form.is_valid():
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.url = form.cleaned_data['url']
            bookmark.save()
            return redirect('bookmark:list')
    else:
        form = BookmarkForm(instance=bookmark)
    return render(request, 'bookmark/edit.html', {
        'bookmark': bookmark,
        'form': form,
    })

def delete(request, pk):
    bookmark = get_object_or_404(Bookmark, pk=pk)

    if request.method == 'POST':
        bookmark.delete()
        return redirect('bookmark:list')

bookmark/templates/bookmark/edit.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}


{% block content %}
<section id="container">
    <header id="header">
        <div><img src="{% static 'img/bookmark.png' %}" alt="북마크아이콘"></div>
        <div>BOOK-MARK</div>
    </header>

    <section class="btn_container">
        <button class="home"><a href="{% url 'bookmark:list' %}" class="home">HOME</a></button>
        <button class="create active"><a href="{% url 'bookmark:new' %}" class="create active">CREATE</a></button>
    </section>


    <section id="edit_container">

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="create" type="submit" value="수정">
        </form>

    </section>

</section>
{% endblock %}

bookmark/templates/bookmark/layout.html
{% extends 'layout.html' %}

bookmark/templates/bookmark/list.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}


{% block content %}

<section id="container">
    <header id="header">
        <div><img src="{% static 'img/bookmark.png' %}" alt="북마크아이콘"></div>
        <div>BOOK-MARK</div>
    </header>

    <section class="btn_container">
        <button class="home active"><a href="{% url 'bookmark:list' %}" class="active home">HOME</a></button>
        <button class="create"><a href="{% url 'bookmark:new' %}" class="create">CREATE</a></button>
    </section>

    {% if list %}
    <section id="over_container">
        <div class="scroll_inner">

            {% for bookmark_list in list %}
            <article class="list01">
                <span class="site_name">{{ bookmark_list.site_name }}</span>
                <span class="line"></span>
                <span class="site_url"><a href="#">{{ bookmark_list.url }}</a></span>
                <div class="form_container">
                    <a href="{% url 'bookmark:edit' bookmark_list.id %}">edit</a>
                    <form action="{% url 'bookmark:delete' bookmark_list.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="delete">
                    </form>
                </div>
            </article>
            {% endfor %}

        </div>
    </section>

    {% else %}

    <div>
        <div class="empty_area">
            <p>
                북마크 항목이 비어있습니다. <br>
                create를 눌러 새 북마크를 생성해보세요.
            </p>
        </div>
    </div>
    {% endif %}

</section>
{% endblock %}

bookmark/templates/bookmark/new.html
{% extends 'layout.html' %} {% load static %} {% block head %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

{% endblock %} {% block content %}
<section id="container">
  <header id="header">
    <div><img src="{% static 'img/bookmark.png' %}" alt="북마크아이콘" /></div>
    <div>BOOK-MARK</div>
  </header>

  <section class="btn_container">
    <button class="home">
      <a href="{% url 'bookmark:list' %}" class="home">HOME</a>
    </button>
    <button class="create active">
      <a href="{% url 'bookmark:new' %}" class="create active">CREATE</a>
    </button>
  </section>

  <section id="edit_container">
    <form
      action=""
      method="post"
      enctype="multipart/form-data"
      autocomplete="off"
    >
      {% csrf_token %} {{ form.as_p }}
      <input class="create" type="submit" value="추가" />
    </form>
  </section>
</section>
{% endblock %}

config/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>bookmark</title>
            {% block head %}
            {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>